name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: welcome message
          run: |
            echo "My First Github Action Job"
            ls -lrat
            cat README.md
        - name: Generate Artwork
          run: cowsay -f dragon "Rub for cover, I am a DRAGON....RAWR" >> dragon.txt
        
        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md
