name: ascii Workflow

on: 
  push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install cowsay program
          run: sudo apt-get install cowsay -y

        - name: list repo files
          run: ls -lrat
            
        - name: Execute shell script
          run: ./ascii-script.sh

        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md
