name: added multi jobs

on: 
  push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Execure cowsay command
          run: cowsay -f dragon "Rub for cover, I am a DRAGON....RAWR" >> dragon.txt
              
        - name: upload dragon artifact
          uses: actions/upload-artifact@v4
          with:
            name: dragon-artifact
            path: dragon.txt

    build_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-artifact

        - name: Test Files exists
          run: grep -i "dragon" dragon.txt

    build_job_3:
        needs: [build_job_2, build_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-artifact
            
        - name: Read file
          run: cat dragon.txt
        
        - name: Deploys
          run: echo deploying... .. .
                            